name: use-local-secret
on:
  workflow_dispatch:
    inputs: 
      USER_SECRET:
        description: "secret_value"
        required: true
        

jobs:
  secure-job:
    runs-on: ubuntu-latest
    steps:
      - name: mask secret
        shell: bash
        run: |
          : # no-op so the step header is just "Run :"
          val=${{ inputs.USER_SECRET }}
          echo "::add-mask::$val"
