name: test-mask
on:
  workflow_dispatch:
    inputs:
      user_secret:
        description: "Secret value"
        required: true
        type: string

jobs:
  mask-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secret
        shell: bash
        run: |
          set +x
          val="${{ inputs.user_secret }}"
          echo "::add-mask::${val}"

      - name: Test logs
        shell: bash
        run: |
          val="${{ inputs.user_secret }}"
          echo "This will be masked: $val"

