name: final-mask
on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: "Secret value"
        required: true
        type: string

jobs:
  mask-job:
    runs-on: ubuntu-latest
    outputs:
      SECRET_OUT: ${{ steps.emit.outputs.secret }}   # expose step output at job level
    steps:
      - name: Mask secret (no echo)
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const p = process.env.GITHUB_EVENT_PATH;
            const evt = JSON.parse(fs.readFileSync(p, 'utf8'));
            const secret = evt.inputs.secret_value;
            core.setSecret(secret);

      - id: emit
        run: |
          echo "secret=${{ inputs.secret_value }}" >> $GITHUB_OUTPUT

      - name: Check size in mask-job
        run: |
          echo -n "${{ inputs.secret_value }}" | wc -c

  use-secret-job:
    runs-on: ubuntu-latest
    needs: mask-job
    steps:
      - name: Check size of secret passed from previous job
        run: |
          secret="${{ needs.mask-job.outputs.SECRET_OUT }}"
          echo "Secret is: $secret"   # will print masked as ***
          echo -n "$secret" | wc -c
