name: test-mask-1
on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: "Secret value"
        required: true
        type: string

jobs:
  mask-job:
    runs-on: ubuntu-latest
    steps:
      # Register the mask without printing the value
      - name: Mask secret (no echo)
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const p = process.env.GITHUB_EVENT_PATH;
            const evt = JSON.parse(fs.readFileSync(p, 'utf8'));
            const secret = evt.inputs.secret_value;
            core.setSecret(secret); // registers mask; nothing printed
  print-job:
    runs-on: ubuntu-latest
    steps:
      # Your original step — now safely redacts to ***
      - name: Test logs
        shell: bash
        run: |
          key_secret_val="${{ inputs.secret_value }}"
          echo "This will be masked: $key_secret_val"
    
