name: KeyVault Secret Update_secret_passJOb

on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: "Enter the secret value"
        required: true
        type: string

jobs:
  mask-secret:
    runs-on: ubuntu-latest
    outputs:
      masked_secret: ${{ steps.set-secret.outputs.secret }}
    steps:
      - name: Mask and set secret
        id: set-secret
        uses: actions/github-script@v7
        with:
          script: |
            const secret = "${{ github.event.inputs.secret_value }}";

            // Mask so it won’t show in logs
            core.setSecret(secret);

            // Pass to next job
            core.setOutput("secret", secret);

  use-secret:
    runs-on: ubuntu-latest
    needs: mask-secret
    steps:
      - name: Show masked secret usage
        run: |
          echo "Using secret in this job"
          echo "Secret value: ${{ needs.mask-secret.outputs.masked_secret }}"
