name: KeyVault Secret Update_secret_passJOb

on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: "Enter the secret value"
        required: true
        type: string

jobs:
  mask-secret:
    runs-on: ubuntu-latest
    outputs:
      masked_secret: ${{ steps.set-secret.outputs.secret }}
    steps:
      - name: Mask and set secret
        id: set-secret
        uses: actions/github-script@v7
        env:
          SECRET_FROM_INPUT: ${{ github.event.inputs.secret_value }}
        with:
          script: |
            const secret = process.env.SECRET_FROM_INPUT || '';
            core.setSecret(secret);           // mask in logs
            core.setOutput('secret', secret); // expose as output

  use-secret:
    runs-on: ubuntu-latest
    needs: mask-secret
    steps:
      - name: Check secret length (without revealing it)
        env:
          SECRET: ${{ needs.mask-secret.outputs.masked_secret }}
        run: |
          if [ -z "$SECRET" ]; then
            echo "Secret is empty"
            exit 1
          fi
          len=${#SECRET}
          echo "Secret length: $len"

          min_len=8
          max_len=256
          if [ "$len" -lt "$min_len" ]; then
            echo "❌ Secret too short (min $min_len)."
            exit 1
          fi
          if [ "$len" -gt "$max_len" ]; then
            echo "❌ Secret too long (max $max_len)."
            exit 1
          fi


          echo "✅ Secret length is within the allowed range."

