name: KeyVault Secret Update_secret_passJOb

on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: "Enter the secret value"
        required: true
        type: string

jobs:
  mask-secret:
    runs-on: ubuntu-latest
    outputs:
      masked_secret: ${{ steps.set-secret.outputs.secret }}
    steps:
      - name: Mask and set secret
        id: set-secret
        uses: actions/github-script@v7
        with:
          script: |
            const fs =require('fs')
            const p = process.env.GITHUB_EVENT_PATH;
            const evt = JSON.parse(fs.readFileSync(p, 'utf8'));
            const secret = evt.inputs.secret_value;
            core.setSecret(secret)

  use-secret:
    runs-on: ubuntu-latest
    needs: mask-secret
    steps:
      - name: Show masked secret usage
        run: |
          echo "Using secret in this job"
          echo "Secret value: ${{ needs.mask-secret.outputs.masked_secret }}"
